# Homebrew formula for the Ampbase supervisor.
#
# GENERATED — do not edit in the tap. The source lives at
# supervisor/homebrew/ampbase.rb in the ampbase repo; the supervisor release
# workflow fills in the url, sha256 and version and pushes the result here.
# Editing this file directly is overwritten by the next release.
#
# The artifact is fetched from ampbase.io/releases rather than GitHub
# Releases because the ampbase repo is private; the release workflow uploads
# to the ampbase-supervisor-releases Tigris bucket, which the main app serves
# publicly via a [[statics]] block. That is also why this formula is
# hand-authored instead of generated by cargo-dist, whose publishing model
# assumes GitHub Releases (a deviation from the RFC-012 Addendum).
class Ampbase < Formula
  desc "Universal OpAMP supervisor for telemetry, AI coding, and eBPF security agents"
  homepage "https://ampbase.io"
  url "https://ampbase.io/releases/v0.15.2/ampbase-universal-apple-darwin.tar.gz"
  sha256 "78391bcdc92917b1aa864c46eb95d555c676a507f03af04aca898208a7398bfb"
  version "0.15.2"
  license "LicenseRef-Ampbase-CSA"

  # One universal binary, Intel and Apple Silicon. Linux installs via
  # https://ampbase.io/install.sh, which serves per-arch musl builds.
  depends_on :macos

  def install
    bin.install "ampbase-universal-apple-darwin" => "ampbase"
    prefix.install "LICENSE"
  end

  # Deliberately NO `service do` block. `brew services` would generate its
  # own launchd plist for this binary, competing with the one `ampbase
  # enroll` writes and bootstraps — two managers, two definitions, one
  # service. Enroll owns the service; brew owns the binary.

  def caveats
    <<~EOS
      Enroll this Mac against a channel:
        sudo ampbase enroll --key <agent-key> --endpoint <opamp-endpoint>

      Add --user to enroll without sudo, as a per-user LaunchAgent.
      Your channel's get-started page has the exact command, pre-filled.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ampbase --version")
  end
end
